{% set version = "2.69" %}

package:
    name: autoconf
    version: {{ version }}

source:
    fn: autoconf-{{ version }}.tar.gz
    url: http://ftp.gnu.org/gnu/autoconf/autoconf-{{ version }}.tar.gz
    sha256: 954bd69b391edc12d6a4a51a2dd1476543da5c6bbf05a95b59dc0dd6fd4c2969

build:
    number: 4
    skip: True  # [win]

requirements:
    build:
        - m4
        - perl
    run:
        - m4
        - perl

test:
    commands:
        - autoconf --help

about:
    home: http://www.gnu.org/software/autoconf/
    license: GPL 3
    summary: Extensible M4 macros that produce shell scripts to configure software source code packages.

extra:
    recipe-maintainers:
        - jakirkham
        - ocefpaf
